### ISSUE TITLE
Endpoints y lógica de registro

### ISSUE THREAD

**Issue by devEstivenValencia** [devEstivenValencia/No-Country-RRHH#13]
Deben cumplirse los siguientes requerimientos

### Endpoints

Deben desarrollarse y exponerse los siguientes endpoints.

- [x] `POST` `/account/enterprise/register`: registra una nueva empresa.
- [x] `PUT` `/account/enterprise/modify`: modifica información de una empresa.

### Requisitos de la información

Deben cumplirse las siguientes reglas sobre la información.

- [x] El email y password deben ser encriptados.

**Comment by devEstivenValencia** [comment]
### Interfaces de solicitud

#### `POST` `/account/enterprise/register`

```JSON5
headers: {
  Authorization: "Bearer token", // Token de sesión
},
body: {
  company_name: "...", // Nombre de la empresa
  credentials: { // encrypted
    email: "...",
    password: "...",
  },
  contact: { // encrypted
    email: "...",
    phone: "",
  },
}
```

#### `PUT` `/account/enterprise/modify`

```JSON5
headers: {
  Authorization: "Bearer token", // Token de sesión
},
body: {
  company_name: "...", // Nombre de la empresa
  contact: { // encrypted
    email: "...",
    phone: "",
  },
}
```

### Códigos de respuesta

- `/account/enterprise/register` : `201 Created` `400 Bad request`
- `/account/enterprise/modify` : `200 OK` `401 Unauthorized` `400 Bad request`

### Interfaces de respuesta:

#### `/account/enterprise/register`

```JSON5
"201 Created"

{
  "session": "...", // Token de sesión
  "user" : {} // Información relacionada del usuario 
}
```

#### `/account/enterprise/register`

```JSON5
"400 Bad request"

{
  "error": "BAD_REQUEST"
}
```

#### `/account/enterprise/modify`

```JSON5
"200 OK"

{
  "success": true
}

"401 Unauthorized"

{ "error": "UNAUTHORIZED" }

"400 Bad request"

{ "error": "BAD_REQUEST" }
```

**Comment by YagoGomez83** [comment]
Se creo la URL http://54.85.163.34, para que pueden pobrabar los endpoint
