### ISSUE TITLE
Endpoints y lógica de sesión

### ISSUE THREAD

**Issue by devEstivenValencia** [devEstivenValencia/No-Country-RRHH#3]
Deben cumplirse los siguientes requerimientos

### Endpoints

Deben desarrollarse y exponerse los siguientes endpoints.

- [x] `POST` `/session/login` : inicia una sesión debe devolver información asociada a la cuenta y el token.
- [x] `DELETE` `/session/logout` : cierra una sesión.
- [x] `POST` `/session/validate` : valida si la sesión existe.

### Requisitos de la información

Deben cumplirse las siguientes reglas sobre la información.

- [x] La sesión deberá dejar de tener validez cada 7 días.
- [x] El `email` y `password` debe ser información encriptada.
- [x] La `password` debe cumplir con el formato de contraseña segura. 
_regex_: `/^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/`

**Comment by devEstivenValencia** [comment]
### Interfaces de solicitud

#### `POST` `/session/login`

```JSON5
body: {
  "email": "...",
  "password" : "..." // encrypted
}
```

#### `DELETE` `/session/logout`

```JSON5
headers: {
  "Authorization": "Bearer token" // Token de sesión
},
body: {
  "session": "..." // Token de sesión
}
```

#### `POST` `/session/validate`

```JSON5
headers: {
  "Authorization": "Bearer token" // Token de sesión
},
body: {
  "session": "..." // Token de sesión
}
```

### Códigos de respuesta

- `/session/login` : `200 OK`
- `/session/logout` : `200 OK` `400 Bad Request` `404 Not Found`
- `/session/validate` : `200 OK` `404 Not Found`

### Interfaces de respuesta:

#### `/session/login`

```JSON5
"200 OK"

{
  "session": "...", // Token de sesión
  "user" : {} // Información relacionada del usuario 
}

```

#### `/session/logout`

```JSON5
"200 OK"

{ "success": true }

"400 Bad Request"

{ "error": "INVALID_TOKEN" }

"404 Not Found"

{ "error": "SESSION_NOT_FOUND" }
```

#### `/session/validate`

```JSON5
"200 OK"

{ "success": true }

"404 Not Found"

{ "error": "SESSION_NOT_FOUND" }
```

**Comment by YagoGomez83** [comment]
Se crearon los endpoint, se realizaron pruebas, donde se verifico las validaciones y respuestas de las mismas.

**Comment by devEstivenValencia** [comment]
`password` y `email` al iniciar sesion debe estar encriptado
